import type { Metadata } from "next";
import { Geist_Mono, Manrope, Open_Sans } from "next/font/google";
import "./globals.css";

/** Display / títulos — variables en app/globals.css (--font-manrope). */
const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

/** Cuerpo: Open Sans; peso base en --font-weight-body (globals.css). 300/600/700 para light/semibold/bold. */
const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
  weight: ["300", "400", "600", "700"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${manrope.variable} ${openSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
